doctrine:
  dbal:
    connections:
      default:
        driver: 'pdo_pgsql'
        server_version:   '11'
        charset:    UTF8
        host:       '%db.postgresql.host%'
        port:       "%db.postgresql.port%"
        dbname:     '%db.postgresql.dbname%'
        user:       '%db.postgresql.user%'
        password:   '%db.postgresql.password%'
    types:
      uuid_binary: Ramsey\Uuid\Doctrine\UuidBinaryType
  orm:
    auto_generate_proxy_classes: '%kernel.debug%'
    naming_strategy: doctrine.orm.naming_strategy.underscore
    auto_mapping: true
