version: "3.7"

services:
  php:
    container_name: ${APP_COMPOSE_PROJECT_NAME}_php
    image: temafey/php7.4-dev
    networks:
      - micro-backend
    user: 1000:1000
    volumes:
      - ~/.composer/cache/:/.composer_cache/:rw
      - .:/app:rw
    working_dir: /app
    restart: on-failure
    command: '/app/bin/console swoole:server:run'
    ports:
      - 9501:9501
      - 9200:9200

  nginx:
    container_name: ${APP_COMPOSE_PROJECT_NAME}_nginx
    image: nginx
    networks:
      - micro-backend
    working_dir: '/app'
    volumes:
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/app
    depends_on:
      - php-fpm
    ports:
      - 80:80

  php-fpm:
    container_name: ${APP_COMPOSE_PROJECT_NAME}_php_fpm
    image: temafey/php7.4-dev-fpm
    networks:
      - micro-backend
    user: 1000:1000
    environment:
      PHP_IDE_CONFIG: serverName=docker
    volumes:
      - ~/.composer/cache/:/.composer_cache/:rw
      - ./:/app:rw
    working_dir: /app

  tasks:
    container_name: ${APP_COMPOSE_PROJECT_NAME}_tasks
    image: temafey/php7.4-dev
    networks:
      - micro-backend
    user: 1000:1000
    volumes:
      - .:/app:rw
    working_dir: /app
    restart: on-failure
    command: '/app/bin/console enqueue:consume -c task'

networks:
  micro-backend:
    name: micro-backend
    driver: bridge
